version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.7
  build:
    commands:
      - aws s3 cp s3://private-conf/apisite/conf.json .
artifacts:
  files:
    - ./*.py
    - conf.json
    - requirements.txt
    - .ebextensions/*
  name: eb-build
  discard-paths: no
